#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

quiet=0
if [[ "${1:-}" == "--quiet" ]]; then
  quiet=1
fi

resolve_hub_root() {
  local candidate="${DT_HUB_ROOT:-${D_T_HUB_ROOT:-$HOME/D_T_SYSTEM_HUB}}"
  if [[ -n "${candidate}" && -d "${candidate}" ]]; then
    (cd "${candidate}" && pwd)
    return 0
  fi
  (cd "${WORKSPACE_ROOT}" && pwd)
}

HUB_ROOT="$(resolve_hub_root)"
if [[ -d "${HUB_ROOT}/D_T_System" ]]; then
  RUNTIME_BASE="${HUB_ROOT}/D_T_System"
else
  RUNTIME_BASE="${WORKSPACE_ROOT}/D_T_System"
fi

RUNTIME_DIR="${DT_RUNTIME_DIR:-${RUNTIME_BASE}/runtime/vscodium}"
RUNTIME_FILE="${DT_RUNTIME_FILE:-${RUNTIME_DIR}/runtime.env}"
OVERRIDE_FILE="${DT_RUNTIME_OVERRIDE_FILE:-${RUNTIME_BASE}/config/vscodium_runtime.env}"

mkdir -p "${RUNTIME_DIR}"

WORKSPACE_FROM_ENV="${DT_WORKSPACE_ROOT:-${WORKSPACE_ROOT}}"
SESSION_ID="${DT_RUNTIME_SESSION_ID:-}"
if [[ -z "${SESSION_ID}" ]]; then
  SESSION_ID="${VSCODE_PID:-${VSCODIUM_PID:-}}"
fi
if [[ -z "${SESSION_ID}" ]]; then
  SESSION_ID="codex-$$"
fi

UPDATED_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

TMP_FILE="$(mktemp "${RUNTIME_FILE}.tmp.XXXXXX")"

cat > "${TMP_FILE}" <<EOF_INNER
# Auto-generated by scripts/ops/dt_hub_runtime_sync.sh
# Single runtime source for MCP servers launched during active editor sessions.
DT_HUB_ROOT="${HUB_ROOT}"
D_T_HUB_ROOT="${HUB_ROOT}"
DT_WORKSPACE_ROOT="${WORKSPACE_FROM_ENV}"
WORKSPACE_ROOT="${WORKSPACE_FROM_ENV}"
DT_RUNTIME_FILE="${RUNTIME_FILE}"
DT_RUNTIME_UPDATED_AT="${UPDATED_AT}"
DT_RUNTIME_SESSION_ID="${SESSION_ID}"

# Shared MCP runtime defaults
LOG_LEVEL="${LOG_LEVEL:-INFO}"
DEFAULT_MODEL="${DEFAULT_MODEL:-gpt-4o-mini}"
DEFAULT_THINKING_MODE_THINKDEEP="${DEFAULT_THINKING_MODE_THINKDEEP:-low}"
EOF_INNER

if [[ -f "${OVERRIDE_FILE}" ]]; then
  {
    echo
    echo "# Hub-managed overrides"
    # Keep only simple KEY=VALUE assignments.
    grep -E '^[A-Za-z_][A-Za-z0-9_]*=' "${OVERRIDE_FILE}" || true
  } >> "${TMP_FILE}"
fi

mv "${TMP_FILE}" "${RUNTIME_FILE}"
chmod 600 "${RUNTIME_FILE}"

if [[ "${quiet}" -eq 0 ]]; then
  echo "[+] D_T runtime source refreshed: ${RUNTIME_FILE}" >&2
fi

printf '%s\n' "${RUNTIME_FILE}"
